//
//  Constants.swift
//  Mena App
//
//  Created by Shoaib_iOSDeveloper on 08/06/2024.
//

import Foundation

struct Constants {
    static let string = Constants()
    
    
    let writeSomething = "Write Something"
    let skip = "Skip"
    let getStarted = "Get Started"
    let pageTitle1 = "Currency in your contact"
    let pageTitle2 = "Accessible to everyone"
    let pageTitle3 = "Step into the mena world"
    let pageDescriptionText1 = "Lorem ipsum dolor sit amet consectetur. Amet velit tempor massa auctor. Enim nulla tristique tempus pulvinar ut eget neque. Felis lectus porta sit ac urna amet pulvinar. Proin lobortis ac vivamus consectetur duis egestas sit adipiscing."
    let pageDescriptionText2 = "Lorem ipsum dolor sit amet consectetur. Amet velit tempor massa auctor. Enim nulla tristique tempus pulvinar ut eget neque. Felis lectus porta sit ac urna amet pulvinar. Proin lobortis ac vivamus consectetur duis egestas sit adipiscing."
    let pageDescriptionText3 = "Lorem ipsum dolor sit amet consectetur. Amet velit tempor massa auctor. Enim nulla tristique tempus pulvinar ut eget neque. Felis lectus porta sit ac urna amet pulvinar. Proin lobortis ac vivamus consectetur duis egestas sit adipiscing."
    let login = "Login"
    let enterYourDetail = "Enter Your Details to Login!"
    let password = "Password"
    let enterYourPassword = "Enter Your password"
    let unlock = "Unlock"
    let create = "Create"
    let enterYourWalletPassword = "Enter Your Wallet password"
    let confirmYourPassword = "Confirm your password"
    let menaWallet = "Mena Wallet"
    let nowItsEasyToOpen = "Now it’s easy to open your wallet"
    let walletPassword = "Wallet Password"
    let confirmPassword = "Confirm Password"
    let home = "Home"
    let payment = "Payment"
    let history = "History"
    let setting = "Setting"
    let changePassword = "Change Password"
    let viewPrivateKey = "View Private Key"
    let viewSeedWords = "View Seed Words"
    let deleteWallet = "Delete Wallet"
    let changedBankDetails = "Change Bank Details"
    let receive = "Receive"
    let send = "Send"
    let refill = "Refill"
    let balance = "Balance"
    let currency = "Currency"
    let recentTransaction = "Recent Transactions"
    let welcomeBack = "Welcome Back !"
    let scanWithQR = "Scan with QR Code"
    let NFC = "NFC"
    let recieveWithQR = "Receive with QR Code"
    let recieveNowBySharing = "Receive now by sharing your QR code with other"
    let waitingForNFC = "Waiting for NFC...."
    let updateBankDetail = "Update bank details"
    let accountName = "Account Name"
    let enterYourAccountName = "Enter Your Account Name"
    let sortCard = "Sort Card"
    let enterYourSortCard = "Enter Your Sort Card"
    let accountNumber = "Account Number"
    let enterYourAccountNo = "Enter Your Account Number"
    let accountCountry = "Account Country"
    let selectYourAccountCountry = "Select Your Account Country"
    let update = "Update"
    let refillBalance = "Re-Fill Balance"
    let amount = "Amount"
    let enterYourAmount = "Enter Your Amount"
    let currencyType = "Currency Type"
    let selectYourCurrency = "Select Your Currency"
    let selectCoin = "Select Coin"
    let selectYourCoin = "Select Your Coin"
    let re_Fill = "Re-Fill"
    let enterYourCurrentPassword = "Enter Your Current Password"
    let newPassword = "New Password"
    let enterYourNewPassword = "Enter Your New Password"
    let enterConfirmPassword = "Enter Confirm Password"
    let confirm = "Confirm"
    let address = "Address"
    let enterYourAddress = "Enter Your Address"
    let qrCode = "QR Code"
    let warning = "Warning"
    let ifYouHaveBeenAsked = "if you have been asked to pass the private key to someone else please STOP what you are doing now! And click 'Cancel' below 👇, Only copy the Private key if you know what you are doing!!! Giving someone else your Private Key could result in losing your funds 😢"
    let showkey = "Show Key"
    let importExistingWallet = "Import Existing Wallet"
    let nowItsOpenToYourExisting = "Now its open to your existing wallet"
    let mnemonicWords = "Mnemonic Words"
    let privateKey = "Private Key"
    let importUsingPrivateKey = "Import Using Private Key"
    let importt = "Import"
    let importUsingMnemonicWords = "Import Using Mnemonic words"
    let nowItsOpenToYourOwnWallet = "Now its open to your own wallet"
    let enterSeedHere = "Enter Seed Here"
    let currentPassword = "Current Password"
    let sendCoin = "Send Coin"
    let areYouSure = "Are you sure?"
    let deletingWalletMayResult = "Deleting Wallet may result in permanantely losing access to your account.\nDo you wish to continue?"
    let Cancel = "Cancel"
    let allRefills = "All Refills"
    let purpose = "Purpose"
    let holderName = "Holder Name"
    let enterPrivateKey = "Enter private key"
    let enterPublicKey = "Enter public key"
    
    
   
}
